title: IIT-K Traveller Documentation
description: A guide to understanding the IITK Traveller Esolang
theme: just-the-docs
mermaid:
  version: "9.3.0"
callouts:
  info:
    title: Information
    color: green
search:
  button: true
